# Generated by Django 4.0.5 on 2022-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('Setter', 'Setter'), ('Admin', 'Admin')], max_length=25),
        ),
    ]
