# Generated by Django 4.0.5 on 2022-07-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
